# Generated by Django 4.1.7 on 2023-03-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="nicho_mercado",
            field=models.CharField(
                choices=[("P", "Presencial"), ("H", "Híbrido"), ("HO", "Home_oficce")],
                max_length=3,
                verbose_name="Tipo da vaga",
            ),
        ),
    ]
