# Generated by Django 4.1.7 on 2023-03-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0002_alter_empresa_nicho_mercado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="nicho_mercado",
            field=models.CharField(
                choices=[("M", "Marketing"), ("N", "Nutrição"), ("D", "Design")],
                max_length=3,
            ),
        ),
    ]
