# Generated by Django 4.1.7 on 2023-03-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0003_alter_empresa_nicho_mercado"),
    ]

    operations = [
        migrations.AddField(
            model_name="vagas",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
